from __future__ import annotations

from io import BytesIO
import textwrap
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter


DISCLAIMER = (
    "REVIEW AID ONLY. This pack records the reviewed claim-file state at the generation "
    "time. It is not a coverage, causation, liability, fraud, reserve, settlement or "
    "recoverability determination."
)


def _display(value: Any) -> str:
    if value is None:
        return "Not established"
    if isinstance(value, bool):
        return "Yes" if value else "No"
    if isinstance(value, dict):
        if "raw" in value:
            return str(value["raw"])
        if "value" in value:
            unit = value.get("unit")
            return f"{value['value']} {unit}".strip() if unit else str(value["value"])
        return "; ".join(f"{key}: {_display(item)}" for key, item in value.items())
    if isinstance(value, list):
        return ", ".join(_display(item) for item in value)
    return str(value)


def _pdf_safe(value: str) -> str:
    return value.encode("cp1252", "replace").decode("cp1252").replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _pdf_lines(snapshot: dict[str, Any]) -> list[str]:
    claim = snapshot["claim"]
    summary = snapshot["summary"]
    lines = [
        "MARITIME CLAIM FILE PACK",
        DISCLAIMER,
        "",
        f"Claim reference: {claim['claim_reference']}",
        f"Vessel: {claim['vessel_name']}",
        f"IMO: {claim.get('imo_number') or 'Not recorded'}",
        f"Status: {claim['status']}",
        f"Incident date: {claim['incident_date']}",
        f"Generated at: {snapshot['generated_at']}",
        f"Generated by: {snapshot['generated_by']['full_name']}",
        f"Snapshot schema: {snapshot['snapshot_schema_version']}",
        "",
        "REVIEW STATE",
        f"State: {summary['review_state']}",
        f"Approved facts: {summary['approved_fact_count']}",
        f"Open conflicts: {summary['open_conflict_count']}",
        f"Outstanding requirements: {summary['outstanding_requirement_count']}",
        f"Open actions: {summary['open_task_count']}",
        f"Open financial flags: {summary['open_financial_flag_count']}",
        "",
        "APPROVED FACTS AND EVIDENCE",
    ]
    for row in snapshot["evidence_matrix"]["rows"]:
        if row.get("fact_id") is None:
            continue
        lines.append(f"{row['topic']}: {_display(row.get('fact_value'))} [{row['status']}]")
        for source in row.get("supporting_evidence", []):
            current = "current" if source["document_is_current"] else "superseded"
            locator = source.get("source_locator_value") or "location not stated"
            lines.append(
                f"  Source: {source['document_name']} v{source['document_version']} "
                f"({current}; {locator})"
            )
            if source.get("source_quote"):
                lines.append(f"  Quote: {source['source_quote']}")
    lines.extend(["", "OPEN CONFLICTS"])
    conflicts = [
        conflict
        for row in snapshot["evidence_matrix"]["rows"]
        for conflict in row.get("conflicting_evidence", [])
        if conflict["status"] == "open"
    ]
    if conflicts:
        for conflict in conflicts:
            lines.append(
                f"{conflict['topic']} [{conflict['materiality']}]: {conflict['description']}"
            )
    else:
        lines.append("No open evidence conflicts are recorded in this snapshot.")

    lines.extend(["", "OUTSTANDING EVIDENCE"])
    outstanding = snapshot["outstanding_requirements"]
    if outstanding:
        for item in outstanding:
            lines.append(
                f"{item['document_label']} [{item['priority']}/{item['status']}]: {item['reason']}"
            )
    else:
        lines.append("No outstanding document requirements are recorded in this snapshot.")

    lines.extend(["", "OPEN ACTIONS"])
    if snapshot["open_tasks"]:
        for task in snapshot["open_tasks"]:
            due = f"; due {task['due_date']}" if task.get("due_date") else ""
            lines.append(f"{task['title']} [{task['priority']}]{due}")
    else:
        lines.append("No open tasks are recorded in this snapshot.")

    lines.extend(["", "FINANCIAL REVIEW"])
    financial = snapshot["financial"]
    if financial["totals_by_currency"]:
        for currency, amount in sorted(financial["totals_by_currency"].items()):
            lines.append(f"Reviewed cost total: {currency} {amount}")
    else:
        lines.append("No reviewed financial total is recorded.")
    for flag in financial["open_flags"]:
        lines.append(f"Open flag [{flag['severity']}]: {flag['title']}")

    lines.extend(["", "APPROVED INITIAL ASSESSMENT"])
    assessment = snapshot.get("approved_assessment")
    if assessment:
        lines.append(
            f"Approved assessment v{assessment['version']} "
            f"({'preliminary' if assessment['is_preliminary'] else 'reviewed'})"
        )
        for section in assessment["sections"]:
            lines.extend(["", section["title"], section["text"]])
    else:
        lines.append("No approved Initial Assessment is included.")

    lines.extend(["", "END OF CONTROLLED SNAPSHOT", DISCLAIMER])
    wrapped: list[str] = []
    for line in lines:
        if not line:
            wrapped.append("")
            continue
        wrapped.extend(textwrap.wrap(str(line), width=94, replace_whitespace=False) or [""])
    return wrapped


def render_pdf(snapshot: dict[str, Any]) -> bytes:
    # Dependency-free, deterministic text PDF. CP1252 characters render through
    # the standard Helvetica font; the XLSX companion preserves full Unicode.
    lines = _pdf_lines(snapshot)
    pages = [lines[index : index + 54] for index in range(0, len(lines), 54)] or [[]]

    objects: list[bytes] = []
    page_object_numbers: list[int] = []
    content_object_numbers: list[int] = []
    for index in range(len(pages)):
        page_object_numbers.append(4 + index * 2)
        content_object_numbers.append(5 + index * 2)

    objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    kids = " ".join(f"{number} 0 R" for number in page_object_numbers)
    objects.append(
        f"<< /Type /Pages /Kids [{kids}] /Count {len(pages)} >>".encode("ascii")
    )
    objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")

    for page_number, (page_lines, content_number) in enumerate(
        zip(pages, content_object_numbers, strict=True)
    ):
        page_object = (
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] "
            f"/Resources << /Font << /F1 3 0 R >> >> /Contents {content_number} 0 R >>"
        ).encode("ascii")
        commands = ["BT", "/F1 9 Tf", "54 790 Td", "12 TL"]
        for line in page_lines:
            commands.append(f"({_pdf_safe(line)}) Tj")
            commands.append("T*")
        commands.extend(
            [
                "ET",
                "BT",
                "/F1 8 Tf",
                f"54 28 Td",
                f"(Controlled claim pack - page {page_number + 1} of {len(pages)}) Tj",
                "ET",
            ]
        )
        stream = "\n".join(commands).encode("cp1252", "replace")
        content_object = (
            f"<< /Length {len(stream)} >>\nstream\n".encode("ascii")
            + stream
            + b"\nendstream"
        )
        objects.extend([page_object, content_object])

    output = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for number, obj in enumerate(objects, start=1):
        offsets.append(len(output))
        output.extend(f"{number} 0 obj\n".encode("ascii"))
        output.extend(obj)
        output.extend(b"\nendobj\n")
    xref = len(output)
    output.extend(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    output.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        output.extend(f"{offset:010d} 00000 n \n".encode("ascii"))
    output.extend(
        (
            f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
            f"startxref\n{xref}\n%%EOF\n"
        ).encode("ascii")
    )
    return bytes(output)


def _style_sheet(sheet, widths: list[int]) -> None:
    header_fill = PatternFill("solid", fgColor="0F766E")
    for cell in sheet[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = header_fill
        cell.alignment = Alignment(vertical="top", wrap_text=True)
    for index, width in enumerate(widths, start=1):
        sheet.column_dimensions[get_column_letter(index)].width = width
    sheet.freeze_panes = "A2"
    sheet.auto_filter.ref = sheet.dimensions
    for row in sheet.iter_rows(min_row=2):
        for cell in row:
            cell.alignment = Alignment(vertical="top", wrap_text=True)


def render_xlsx(snapshot: dict[str, Any]) -> bytes:
    workbook = Workbook()
    summary_sheet = workbook.active
    summary_sheet.title = "Pack Summary"
    summary_sheet.append(["Field", "Value"])
    claim = snapshot["claim"]
    summary = snapshot["summary"]
    summary_rows = [
        ("Control notice", DISCLAIMER),
        ("Claim reference", claim["claim_reference"]),
        ("Vessel", claim["vessel_name"]),
        ("IMO", claim.get("imo_number") or "Not recorded"),
        ("Claim status", claim["status"]),
        ("Incident date", claim["incident_date"]),
        ("Generated at", snapshot["generated_at"]),
        ("Generated by", snapshot["generated_by"]["full_name"]),
        ("Review state", summary["review_state"]),
        ("Approved facts", summary["approved_fact_count"]),
        ("Open conflicts", summary["open_conflict_count"]),
        ("Outstanding requirements", summary["outstanding_requirement_count"]),
        ("Open actions", summary["open_task_count"]),
        ("Open financial flags", summary["open_financial_flag_count"]),
        ("Approved assessment version", summary["approved_assessment_version"] or "None"),
    ]
    for row in summary_rows:
        summary_sheet.append(row)
    _style_sheet(summary_sheet, [32, 110])

    evidence_sheet = workbook.create_sheet("Evidence Matrix")
    evidence_sheet.append(
        [
            "Topic",
            "Approved fact",
            "Status",
            "Source",
            "Version",
            "Current",
            "Locator",
            "Source quote",
            "Open conflicts",
        ]
    )
    for row in snapshot["evidence_matrix"]["rows"]:
        sources = row.get("supporting_evidence") or [{}]
        conflicts = [
            item["description"]
            for item in row.get("conflicting_evidence", [])
            if item["status"] == "open"
        ]
        for source in sources:
            evidence_sheet.append(
                [
                    row["topic"],
                    _display(row.get("fact_value")),
                    row["status"],
                    source.get("document_name", ""),
                    source.get("document_version", ""),
                    source.get("document_is_current", ""),
                    source.get("source_locator_value", ""),
                    source.get("source_quote", ""),
                    "\n".join(conflicts),
                ]
            )
    _style_sheet(evidence_sheet, [28, 36, 20, 32, 10, 10, 24, 60, 60])

    requirements_sheet = workbook.create_sheet("Outstanding Evidence")
    requirements_sheet.append(["Document", "Priority", "Status", "Reason"])
    for item in snapshot["outstanding_requirements"]:
        requirements_sheet.append(
            [item["document_label"], item["priority"], item["status"], item["reason"]]
        )
    _style_sheet(requirements_sheet, [34, 14, 16, 80])

    tasks_sheet = workbook.create_sheet("Open Actions")
    tasks_sheet.append(["Action", "Priority", "Type", "Due date", "Source"])
    for task in snapshot["open_tasks"]:
        tasks_sheet.append(
            [
                task["title"],
                task["priority"],
                task["task_type"],
                task.get("due_date") or "",
                task["source"],
            ]
        )
    _style_sheet(tasks_sheet, [60, 14, 18, 16, 18])

    financial_sheet = workbook.create_sheet("Financial Review")
    financial_sheet.append(
        ["Kind", "Description", "Amount", "Currency", "Review status", "Flag severity"]
    )
    for item in snapshot["financial"]["items"]:
        financial_sheet.append(
            [
                item["document_kind"],
                item["description"],
                item["amount"],
                item["currency"],
                item["review_status"],
                "",
            ]
        )
    for flag in snapshot["financial"]["open_flags"]:
        financial_sheet.append(
            ["open_flag", flag["title"], "", "", flag["status"], flag["severity"]]
        )
    _style_sheet(financial_sheet, [18, 70, 18, 12, 24, 16])

    assessment_sheet = workbook.create_sheet("Approved Assessment")
    assessment_sheet.append(["Section", "Approved text", "Sources"])
    assessment = snapshot.get("approved_assessment")
    if assessment:
        for section in assessment["sections"]:
            assessment_sheet.append(
                [
                    section["title"],
                    section["text"],
                    "\n".join(source["label"] for source in section["sources"]),
                ]
            )
    _style_sheet(assessment_sheet, [34, 110, 55])

    manifest_sheet = workbook.create_sheet("Export Manifest")
    manifest_sheet.append(["Field", "Value"])
    manifest_sheet.append(["Snapshot schema", snapshot["snapshot_schema_version"]])
    manifest_sheet.append(["Generated at", snapshot["generated_at"]])
    manifest_sheet.append(["Review aid only", "true"])
    manifest_sheet.append(["Generation note", snapshot.get("generation_note") or ""])
    _style_sheet(manifest_sheet, [32, 110])

    output = BytesIO()
    workbook.save(output)
    return output.getvalue()
