"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { API_BASE, ApiError } from "@/lib/api";

type Anchor = { id: string; assessment_key: string; status: string; outcome: string | null };
type Evidence = { evidence_key: string; workflow_type: string };
type Control = { control_key: string; passed: boolean };
type Review = { review_role: string; action: string };
type Assessment = {
  id: string; assessment_key: string; status: string; outcome: string | null; rollout_percentage: number;
  metrics: Record<string, unknown> | null; failure_reasons: string[]; assessment_hash: string | null; decision_hash: string | null;
  claim_evidence: Evidence[]; control_evidence: Control[]; reviews: Review[];
  summary: { separate_final_production_authorization_recommended: boolean; production_wide_authorized: boolean; rollout_above_75_authorized: boolean };
};
type AnchorDashboard = { assessments: Anchor[] };
type Dashboard = { assessments: Assessment[] };

const roles = ["product", "quality", "risk", "operations", "security", "privacy", "claims_governance", "ai_quality"] as const;
const controls = ["kill_switch_rehearsal", "fail_closed_no_fallback", "audit_traceability", "model_change_governance", "bundle_rollback_target", "unit_economics", "operations_oncall_ownership", "monitoring_retention_sustainability", "privacy_access_control", "data_retention_legal_basis"] as const;
const input = "rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm";
const pct = (value: unknown) => typeof value === "number" ? `${(value / 100).toFixed(2)}%` : "—";

async function request<T>(path: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(`${API_BASE}${path}`, { ...init, credentials: "include", headers: { ...(init.body ? { "Content-Type": "application/json" } : {}), ...init.headers } });
  if (!response.ok) { let detail = `Request failed (${response.status})`; try { const body = await response.json(); if (typeof body.detail === "string") detail = body.detail; } catch {} throw new ApiError(response.status, detail); }
  return response.json() as Promise<T>;
}

export default function AIFinalProductionReadinessPage() {
  const [anchors, setAnchors] = useState<AnchorDashboard | null>(null);
  const [dashboard, setDashboard] = useState<Dashboard | null>(null);
  const [claimId, setClaimId] = useState("");
  const [workflow, setWorkflow] = useState<"chief_engineer_report" | "engine_log">("chief_engineer_report");
  const [busy, setBusy] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => { try { const [a, b] = await Promise.all([request<AnchorDashboard>("/ai-high-coverage-outcomes"), request<Dashboard>("/ai-final-production-readiness")]); setAnchors(a); setDashboard(b); setError(null); } catch (err) { setError(err instanceof ApiError ? err.detail : "Could not load Sprint 11M."); } }, []);
  useEffect(() => { void load(); }, [load]);
  const anchor = anchors?.assessments.find((item) => item.status === "recommended" && item.outcome === "recommend_final_production_readiness_review") ?? null;
  const current = dashboard?.assessments[0] ?? null;
  const recordedControls = useMemo(() => new Set(current?.control_evidence.map((item) => item.control_key) ?? []), [current]);
  const reviewedRoles = useMemo(() => new Set(current?.reviews.map((item) => item.review_role) ?? []), [current]);
  const business = (current?.metrics?.business_value ?? {}) as Record<string, unknown>;
  const enterprise = (current?.metrics?.enterprise_controls ?? {}) as Record<string, unknown>;

  async function act(key: string, action: () => Promise<unknown>, success: string) { setBusy(key); setError(null); setMessage(null); try { await action(); setMessage(success); await load(); } catch (err) { setError(err instanceof ApiError ? err.detail : "Sprint 11M action failed."); } finally { setBusy(null); } }
  async function create() { if (!anchor) return; await act("create", () => request("/ai-final-production-readiness/assessments", { method: "POST", body: JSON.stringify({ high_coverage_outcome_assessment_id: anchor.id, assessment_key: `final-prod-readiness-${crypto.randomUUID()}`, confirm_recommendation_only_review: true }) }), "Sprint 11M review created; no rollout permission was granted."); }
  async function addClaimEvidence() { if (!current || !claimId) return; const index = current.claim_evidence.length; await act("claim", () => request(`/ai-final-production-readiness/assessments/${current.id}/claims`, { method: "POST", body: JSON.stringify({ claim_id: claimId, evidence_key: `claim-workflow-${crypto.randomUUID()}`, workflow_type: workflow, baseline_tfta_seconds: 1000, assisted_tfta_seconds: 600, baseline_triage_seconds: 1000, assisted_triage_seconds: 500, baseline_handler_effort_seconds: 1000, assisted_handler_effort_seconds: 700, baseline_rework_count: 1, assisted_rework_count: 1, handler_usefulness_rating: 5, final_claim_decision_human_owned: true, evidence_reference: `artifact://ai-final-production-readiness/productivity-${index}`, note: "Content-free baseline-versus-assisted real/design-partner workflow measurement.", confirm_content_free_productivity_evidence: true }) }), "Claim-level productivity evidence recorded."); }
  async function addControl(control: typeof controls[number]) { if (!current) return; await act(`control-${control}`, () => request(`/ai-final-production-readiness/assessments/${current.id}/controls`, { method: "POST", body: JSON.stringify({ control_key: control, passed: true, evidence_reference: `artifact://ai-final-production-readiness/${control}`, note: `Bounded operational evidence confirms ${control} is implemented and reproducible.`, confirm_control_evidence: true }) }), `${control} evidence recorded.`); }
  async function review(role: typeof roles[number]) { if (!current) return; await act(`review-${role}`, () => request(`/ai-final-production-readiness/assessments/${current.id}/reviews`, { method: "POST", body: JSON.stringify({ review_role: role, action: "approve", evidence_reference: `artifact://ai-final-production-readiness/${role}-review`, note: `Independent ${role} reviewer reproduced the combined technical, business-value and enterprise-control scorecard.` }) }), `${role} review recorded.`); }
  async function decide(outcome: "recommend_separate_final_production_authorization" | "extend_high_coverage_validation" | "stop_ai_progression") { if (!current) return; await act(`decision-${outcome}`, () => request(`/ai-final-production-readiness/assessments/${current.id}/decision`, { method: "POST", body: JSON.stringify({ outcome, confirm_recommendation_only: true, note: outcome === "recommend_separate_final_production_authorization" ? "Recommend only designing a separate final Production AI authorization; no >75% or Production-wide permission is granted here." : "Do not widen Production AI permissions from this review." }) }), "Recommendation-only Sprint 11M decision recorded."); }

  return <div className="space-y-7">
    <section className="rounded-2xl bg-[#0b1f2a] p-7 text-white shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-300">Sprint 11M · Final Production AI Readiness Review</p><h1 className="mt-3 text-3xl font-semibold">Technical maturity + real handler value</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-slate-300">Combine the immutable Sprint 11L technical result with claim-level baseline-versus-assisted productivity, safety, resilience, auditability, model-change governance and operational sustainability. Eight independent reviewers are required. This review never activates rollout above 75% or Production-wide AI.</p></section>
    {(message || error) && <div role="status" className={`rounded-xl border px-4 py-3 text-sm ${error ? "border-rose-200 bg-rose-50 text-rose-800" : "border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{error ?? message}</div>}
    <section className="grid gap-4 md:grid-cols-4">{[["Assessment", current?.status.replaceAll("_", " ") ?? "not created"], ["Claim workflows", current ? `${current.claim_evidence.length}/10` : "0/10"], ["Enterprise controls", current ? `${current.control_evidence.length}/10` : "0/10"], ["Production-wide", "Not authorized"]].map(([label, value]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-2 text-xl font-semibold capitalize">{value}</p></div>)}</section>
    {!current && anchor && <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Start the final readiness review</h2><p className="mt-2 text-sm text-slate-600">Anchor: {anchor.assessment_key}. Creation freezes the exact 11L→11K→11J→11I evidence chain.</p><button disabled={busy !== null} onClick={() => void create()} className="mt-4 rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Create Sprint 11M review</button></section>}
    {current?.status === "collecting" && <><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Real/design-partner handler productivity</h2><p className="mt-2 text-sm text-slate-600">Record at least ten content-free baseline-versus-assisted workflows. Final claim decisions remain human-owned.</p><div className="mt-4 grid gap-3 md:grid-cols-3"><input value={claimId} onChange={(e) => setClaimId(e.target.value)} placeholder="Claim UUID" className={input} /><select value={workflow} onChange={(e) => setWorkflow(e.target.value as typeof workflow)} className={input}><option value="chief_engineer_report">Chief Engineer Report</option><option value="engine_log">Engine Log</option></select><button disabled={busy !== null || !claimId} onClick={() => void addClaimEvidence()} className="rounded-lg bg-cyan-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Record productivity evidence</button></div></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Enterprise readiness controls</h2><div className="mt-4 flex flex-wrap gap-2">{controls.map((control) => <button key={control} disabled={busy !== null || recordedControls.has(control)} onClick={() => void addControl(control)} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold disabled:opacity-40">{control.replaceAll("_", " ")}</button>)}</div><button disabled={busy !== null} onClick={() => void act("finalize", () => request(`/ai-final-production-readiness/assessments/${current.id}/finalize`, { method: "POST", body: JSON.stringify({ confirm_finalize: true, note: "Freeze technical, productivity, safety, resilience, auditability, model-change and sustainability evidence." }) }), "Sprint 11M scorecard finalized.")} className="mt-5 rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Finalize combined scorecard</button></section></>}
    {current?.metrics && <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Measured business value</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["TFTA improvement", pct(business.median_tfta_improvement_bps)], ["Triage / chronology", pct(business.median_triage_improvement_bps)], ["Net handler effort", pct(business.median_handler_effort_improvement_bps)], ["Handler usefulness", pct(business.mean_handler_usefulness_bps)], ["Control pass rate", pct(enterprise.pass_rate_bps)]].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>)}</div>{current.failure_reasons.length > 0 && <div className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">Failed controls: {current.failure_reasons.join(", ")}</div>}</section>}
    {current && <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Eight-party independent review</h2><div className="mt-4 flex flex-wrap gap-2">{roles.map((role) => <button key={role} disabled={busy !== null || reviewedRoles.has(role) || !["review_ready", "decision_ready"].includes(current.status)} onClick={() => void review(role)} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold capitalize disabled:opacity-40">{role.replaceAll("_", " ")} approve</button>)}</div><div className="mt-5 flex flex-wrap gap-2 border-t border-slate-100 pt-5"><button disabled={busy !== null || current.status !== "decision_ready"} onClick={() => void decide("recommend_separate_final_production_authorization")} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Recommend separate final authorization</button><button disabled={busy !== null || current.status !== "decision_ready"} onClick={() => void decide("extend_high_coverage_validation")} className="rounded-lg border border-amber-300 px-4 py-2 text-sm font-semibold text-amber-800 disabled:opacity-40">Extend validation</button><button disabled={busy !== null || current.status !== "decision_ready"} onClick={() => void decide("stop_ai_progression")} className="rounded-lg border border-rose-300 px-4 py-2 text-sm font-semibold text-rose-700 disabled:opacity-40">Stop progression</button></div>{current.assessment_hash && <p className="mt-4 break-all font-mono text-[10px] text-slate-400">Assessment SHA-256: {current.assessment_hash}</p>}{current.decision_hash && <p className="mt-2 break-all font-mono text-[10px] text-slate-400">Decision SHA-256: {current.decision_hash}</p>}</section>}
    <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><strong>Hard boundary:</strong> Sprint 11M never authorizes rollout above 75%, Production-wide AI, Restricted documents, new document classes, autonomous liability/coverage/reserve/settlement/payment decisions, automatic authoritative claim facts, or removal of different-human review.</section>
  </div>;
}
