"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";

import { ApiError, createPortalInvitation, getClaim, getPortalWorkspace, proposePortalPublication, reviewPortalPublication, reviewPortalSubmission, revokePortalInvitation } from "@/lib/api";
import type { Claim, PortalWorkspace } from "@/lib/types";

export default function ExternalPortalWorkspacePage() {
  const { id } = useParams<{ id: string }>(); const [claim, setClaim] = useState<Claim | null>(null);
  const [workspace, setWorkspace] = useState<PortalWorkspace>({ invitations: [], submissions: [], publication_proposals: [] });
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [purpose, setPurpose] = useState("Controlled exchange of factual claim updates and requested material.");
  const [oneTimeToken, setOneTimeToken] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { try { const [c, w] = await Promise.all([getClaim(id), getPortalWorkspace(id)]); setClaim(c); setWorkspace(w); setError(""); } catch (e) { setError(e instanceof ApiError ? e.detail : "Portal workspace could not be loaded."); } }
  useEffect(() => { load(); }, [id]);
  async function run(task: () => Promise<unknown>) { setBusy(true); try { await task(); await load(); } catch (e) { setError(e instanceof ApiError ? e.detail : "Portal operation failed."); } finally { setBusy(false); } }
  async function invite() { setBusy(true); try { const created = await createPortalInvitation(id, { participant_name: name, participant_email: email, purpose, expires_in_hours: 72, permission_manifest: ["claim_summary.view", "published_items.view", "submission.create"], published_items: [] }); setOneTimeToken(created.invitation_token || ""); await load(); } catch (e) { setError(e instanceof ApiError ? e.detail : "Invitation could not be created."); } finally { setBusy(false); } }
  if (!claim) return <div className="panel p-6">{error || "Loading…"}</div>;
  return <div><Link href={`/claims/${id}`} className="text-sm font-semibold text-slate-500">← Back to claim</Link>
    <p className="eyebrow mt-5">{claim.claim_reference} · Sprint 9J</p><h1 className="mt-2 text-3xl font-semibold">External Collaboration Portal</h1>
    <p className="mt-2 max-w-4xl text-sm leading-6 text-slate-500">Each invitation is claim-scoped and short-lived. Internal material can become visible only after a separate Manager/Admin approves a publication proposal; privileged correspondence and restricted evidence remain blocked.</p>
    {error ? <div className="mt-5 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div> : null}
    {oneTimeToken ? <div className="mt-5 rounded-xl border border-amber-300 bg-amber-50 p-5"><p className="font-semibold">Copy the one-time invitation token</p><p className="mt-2 break-all font-mono text-xs">{oneTimeToken}</p><p className="mt-2 text-xs">Only its SHA-256 hash is stored.</p></div> : null}
    <div className="mt-6 grid gap-6 xl:grid-cols-[380px_minmax(0,1fr)]"><aside className="panel p-5"><h2 className="section-title">Issue claim-scoped invitation</h2><label className="mt-4 block"><span className="label">Participant name</span><input className="field" value={name} onChange={(e) => setName(e.target.value)} /></label><label className="mt-3 block"><span className="label">Participant email</span><input className="field" type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label className="mt-3 block"><span className="label">Purpose</span><textarea className="field min-h-24" value={purpose} onChange={(e) => setPurpose(e.target.value)} /></label><button className="primary-button mt-4" disabled={busy || !name || !email} onClick={invite}>Create 72-hour invitation</button><p className="mt-3 text-xs text-slate-500">Published-item selection is intentionally explicit; this starter invitation shares no internal item by default.</p></aside>
      <main className="space-y-5"><section className="panel p-5"><h2 className="section-title">Invitations</h2><div className="mt-3 space-y-3">{workspace.invitations.map((x) => <div key={x.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{x.participant_name}</p><p className="text-xs text-slate-500">{x.participant_email} · expires {new Date(x.expires_at).toLocaleString()}</p></div><span className="text-xs font-semibold">{x.status}</span></div><p className="mt-2 text-sm">{x.purpose}</p>{x.status !== "revoked" ? <button className="secondary-button mt-3" onClick={() => { const note = window.prompt("Revocation reason")?.trim(); if (note) run(() => revokePortalInvitation(id, x.id, note)); }}>Revoke access</button> : null}</div>)}{!workspace.invitations.length ? <p className="text-sm text-slate-500">No invitation issued.</p> : null}</div></section>
      <section className="panel p-5"><h2 className="section-title">Four-eyes publication queue</h2><p className="section-subtitle">Propose eligible correspondence or document metadata by source ID. The proposer cannot approve their own proposal.</p><div className="mt-3 space-y-3">{workspace.publication_proposals.map((x) => <div key={x.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{x.title}</p><p className="text-xs text-slate-500">{x.item_type} · {x.source_id}</p></div><span className="text-xs font-semibold">{x.status}</span></div>{x.summary ? <p className="mt-2 text-sm text-slate-600">{x.summary}</p> : null}{x.status === "under_review" ? <div className="mt-3 flex gap-2"><button className="primary-button" onClick={() => { const note = window.prompt("Approval reason")?.trim(); if (note) run(() => reviewPortalPublication(id, x.id, "approve", note)); }}>Approve publication</button><button className="secondary-button" onClick={() => { const note = window.prompt("Rejection reason")?.trim(); if (note) run(() => reviewPortalPublication(id, x.id, "reject", note)); }}>Reject</button></div> : null}</div>)}{!workspace.publication_proposals.length ? <p className="text-sm text-slate-500">No publication proposal.</p> : null}</div>{workspace.invitations.some((x) => x.status !== "revoked") ? <button className="secondary-button mt-4" onClick={() => { const invitation = workspace.invitations.find((x) => x.status !== "revoked"); const sourceId = window.prompt("Eligible correspondence or document source ID")?.trim(); const title = window.prompt("Publication title")?.trim(); if (invitation && sourceId && title) run(() => proposePortalPublication(id, invitation.id, { item_type: "correspondence", source_id: sourceId, title })); }}>Propose correspondence publication</button> : null}</section>
      <section className="panel p-5"><h2 className="section-title">External submissions awaiting human review</h2><div className="mt-3 space-y-3">{workspace.submissions.map((x) => <div key={x.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between"><p className="font-semibold">{x.subject}</p><span className="text-xs">{x.status}</span></div><p className="mt-2 text-sm text-slate-600">{x.body}</p>{x.status === "pending_review" ? <div className="mt-3 flex gap-2"><button className="primary-button" onClick={() => { const note = window.prompt("Promotion reason")?.trim(); if (note) run(() => reviewPortalSubmission(id, x.id, "promote", note)); }}>Promote to correspondence</button><button className="secondary-button" onClick={() => { const note = window.prompt("Rejection reason")?.trim(); if (note) run(() => reviewPortalSubmission(id, x.id, "reject", note)); }}>Reject</button></div> : null}</div>)}{!workspace.submissions.length ? <p className="text-sm text-slate-500">No external submission.</p> : null}</div></section></main></div>
  </div>;
}
