"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ApiError, getFinancialReview, resolveFinancialFlag, updateCostStatus } from "@/lib/api";
import type { CostReviewStatus, FinancialReviewResponse } from "@/lib/types";
export default function FinancialReviewPage(){
 const {id}=useParams<{id:string}>(); const [data,setData]=useState<FinancialReviewResponse|null>(null); const [error,setError]=useState("");
 const load=()=>getFinancialReview(id).then(setData).catch(e=>setError(e instanceof ApiError?e.detail:"Financial review could not be loaded.")); useEffect(()=>{load()},[id]);
 async function setStatus(itemId:string,status:CostReviewStatus){const reason=window.prompt("Reason for status change?");if(!reason)return;await updateCostStatus(id,itemId,status,reason);load()}
 async function resolve(idFlag:string){const note=window.prompt("Resolution/explanation?");if(!note)return;await resolveFinancialFlag(id,idFlag,"explained",note);load()}
 if(!data)return <div className="panel p-6">{error||"Loading financial review…"}</div>;
 return <div><Link href={`/claims/${id}`} className="text-sm font-semibold text-slate-500">← Back to claim</Link><div className="mt-5"><p className="eyebrow">Cost control intelligence</p><h1 className="mt-2 text-3xl font-semibold text-slate-950">Financial review</h1><p className="mt-2 text-sm text-slate-500">Human-reviewed commercial evidence, deterministic flags and reserve history. No automatic recoverability or supplier selection.</p></div>
 <section className="mt-6 grid gap-4 md:grid-cols-3">{Object.entries(data.totals_by_currency).map(([c,v])=><div className="panel p-5" key={c}><p className="metric-label">Reviewed invoice line items</p><p className="metric-value">{c} {Number(v).toLocaleString()}</p></div>)}<div className="panel p-5"><p className="metric-label">Open flags</p><p className="metric-value">{data.flags.filter(f=>f.status==="open").length}</p></div></section>
 <section className="panel mt-6 p-6"><h2 className="section-title">Cost schedule</h2><div className="mt-4 overflow-x-auto"><table className="data-table min-w-[900px]"><thead><tr><th>Description</th><th>Supplier</th><th>Amount</th><th>Category</th><th>Status</th></tr></thead><tbody>{data.items.map(x=><tr key={x.id}><td>{x.description}</td><td>{x.supplier||"—"}</td><td>{x.currency} {Number(x.amount).toLocaleString()}</td><td>{x.category||"—"}</td><td><select value={x.review_status} onChange={e=>setStatus(x.id,e.target.value as CostReviewStatus)} className="field py-1 text-xs"><option value="under_review">Under review</option><option value="potentially_recoverable">Potentially recoverable</option><option value="potentially_non_recoverable">Potentially non-recoverable</option><option value="accepted">Accepted</option><option value="rejected">Rejected</option><option value="paid">Paid</option></select></td></tr>)}</tbody></table></div></section>
 <section className="mt-6 grid gap-6 xl:grid-cols-2"><div className="panel p-6"><h2 className="section-title">Financial flags</h2><div className="mt-4 space-y-3">{data.flags.length?data.flags.map(f=><div key={f.id} className="rounded-lg border border-slate-200 p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold text-slate-900">{f.title}</p><p className="mt-1 text-xs uppercase text-slate-400">{f.flag_type} · {f.severity}</p></div><span className="text-xs font-semibold">{f.status}</span></div><p className="mt-3 text-sm text-slate-600">{f.explanation}</p>{f.status==="open"?<button onClick={()=>resolve(f.id)} className="secondary-button mt-3">Explain / resolve</button>:null}</div>):<p className="text-sm text-slate-500">No current flags.</p>}</div></div>
 <div className="panel p-6"><h2 className="section-title">Quotation comparison</h2><div className="mt-4 space-y-3">{data.quotations.map(q=><div key={q.document_id} className="rounded-lg border border-slate-200 p-4"><p className="font-semibold">{q.supplier||"Quotation"} {q.quotation_number||""}</p><p className="mt-1 text-sm">{q.currency||""} {q.total?Number(q.total).toLocaleString():"—"}</p><p className="mt-2 text-sm text-slate-600">{q.scope_summary||"Scope not yet approved."}</p><p className="mt-2 text-xs text-slate-400">Lead time: {q.lead_time||"—"} · Repair duration: {q.repair_duration||"—"}</p></div>)}</div></div></section>
 <section className="panel mt-6 p-6"><h2 className="section-title">Reserve history</h2><div className="mt-4 space-y-2">{data.reserve_history.map(r=><div key={r.id} className="flex justify-between border-b border-slate-100 py-3"><div><p className="font-medium">{r.currency} {Number(r.amount).toLocaleString()}</p><p className="text-xs text-slate-500">{r.reason}</p></div><span className="text-xs text-slate-400">{new Date(r.created_at).toLocaleString()}</span></div>)}</div></section></div>
}
