"""add durable recovery read renewal authorization

Revision ID: 0128_recovery_durable_read_renewal_authorization
Revises: 0127_recovery_durable_read_health_qualification
"""

from alembic import op
import sqlalchemy as sa

revision = "0128_recovery_durable_read_renewal_authorization"
down_revision = "0127_recovery_durable_read_health_qualification"
branch_labels = None
depends_on = None

AUTH_TABLE = "evidence_recovery_durable_read_renewal_authorizations"
RECEIPT_TABLE = "evidence_recovery_durable_read_renewal_authorization_receipts"


def upgrade() -> None:
    op.create_table(
        AUTH_TABLE,
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("health_qualification_id", sa.Uuid(), nullable=False),
        sa.Column("health_qualification_receipt_id", sa.Uuid(), nullable=False),
        sa.Column("durable_lease_id", sa.Uuid(), nullable=False),
        sa.Column("activation_receipt_id", sa.Uuid(), nullable=False),
        sa.Column("terminal_receipt_id", sa.Uuid(), nullable=False),
        sa.Column("prior_authorization_id", sa.Uuid(), nullable=False),
        sa.Column("phase_k_qualification_id", sa.Uuid(), nullable=False),
        sa.Column("replica_id", sa.Uuid(), nullable=False),
        sa.Column("health_qualification_hash", sa.String(length=64), nullable=False),
        sa.Column("health_request_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("health_qualification_receipt_hash", sa.String(length=64), nullable=False),
        sa.Column("operational_evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("health_state", sa.String(length=20), nullable=False),
        sa.Column("durable_lease_hash", sa.String(length=64), nullable=False),
        sa.Column("lease_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("activation_receipt_hash", sa.String(length=64), nullable=False),
        sa.Column("terminal_receipt_hash", sa.String(length=64), nullable=False),
        sa.Column("prior_authorization_hash", sa.String(length=64), nullable=False),
        sa.Column("phase_k_qualification_hash", sa.String(length=64), nullable=False),
        sa.Column("replica_hash", sa.String(length=64), nullable=False),
        sa.Column("source_file_hash", sa.String(length=64), nullable=False),
        sa.Column("source_file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("local_storage_key_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("recovery_bucket_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("candidate_storage_key_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("source_authority_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("candidate_authority_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("configuration_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("verified_durable_read_count", sa.Integer(), nullable=False),
        sa.Column("integrity_failure_count", sa.Integer(), nullable=False),
        sa.Column("storage_unavailable_count", sa.Integer(), nullable=False),
        sa.Column("route_version_at_request", sa.Integer(), nullable=False),
        sa.Column("integrity_proof_hash", sa.String(length=64), nullable=False),
        sa.Column("request_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("authorization_hash", sa.String(length=64), nullable=False),
        sa.Column("health_qualified_by_id", sa.Uuid(), nullable=False),
        sa.Column("durable_activated_by_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="pending_second_approval", nullable=False),
        sa.Column("authorization_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("requested_by_id", sa.Uuid(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_reason", sa.Text(), nullable=False),
        sa.Column("approved_by_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_reason", sa.Text(), nullable=True),
        sa.Column("rejected_by_id", sa.Uuid(), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("terminal_by_id", sa.Uuid(), nullable=True),
        sa.Column("terminal_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terminal_reason", sa.Text(), nullable=True),
        sa.Column("routable_authority_created", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("durable_read_route_created", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("read_path_switched", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("write_path_switched", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("document_storage_key_mutated", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("authoritative_storage_changed", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("destructive_action_performed", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("s3_delete_performed", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("local_delete_performed", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending_second_approval', 'approved', 'rejected', 'expired', 'invalidated')",
            name="ck_durable_read_renewal_auth_status",
        ),
        sa.CheckConstraint("health_state = 'healthy'", name="ck_durable_read_renewal_auth_healthy_only"),
        sa.CheckConstraint(
            "requested_by_id <> approved_by_id OR approved_by_id IS NULL",
            name="ck_durable_read_renewal_auth_four_eyes",
        ),
        sa.CheckConstraint(
            "health_qualified_by_id <> approved_by_id OR approved_by_id IS NULL",
            name="ck_durable_read_renewal_auth_health_qualifier_split",
        ),
        sa.CheckConstraint(
            "durable_activated_by_id <> approved_by_id OR approved_by_id IS NULL",
            name="ck_durable_read_renewal_auth_activator_split",
        ),
        sa.CheckConstraint("route_version_at_request >= 1", name="ck_durable_read_renewal_auth_route_version"),
        sa.CheckConstraint("source_file_size_bytes >= 0", name="ck_durable_read_renewal_auth_source_size"),
        sa.CheckConstraint("verified_durable_read_count >= 1", name="ck_durable_read_renewal_auth_verified_reads"),
        sa.CheckConstraint("integrity_failure_count = 0", name="ck_durable_read_renewal_auth_no_integrity_failure"),
        sa.CheckConstraint("storage_unavailable_count = 0", name="ck_durable_read_renewal_auth_no_storage_failure"),
        sa.CheckConstraint("routable_authority_created = false", name="ck_durable_read_renewal_auth_no_route_auth"),
        sa.CheckConstraint("durable_read_route_created = false", name="ck_durable_read_renewal_auth_no_durable_route"),
        sa.CheckConstraint("read_path_switched = false", name="ck_durable_read_renewal_auth_no_read_switch"),
        sa.CheckConstraint("write_path_switched = false", name="ck_durable_read_renewal_auth_no_write_switch"),
        sa.CheckConstraint("document_storage_key_mutated = false", name="ck_durable_read_renewal_auth_no_key_mut"),
        sa.CheckConstraint("authoritative_storage_changed = false", name="ck_durable_read_renewal_auth_no_authority"),
        sa.CheckConstraint("destructive_action_performed = false", name="ck_durable_read_renewal_auth_no_destructive"),
        sa.CheckConstraint("s3_delete_performed = false", name="ck_durable_read_renewal_auth_no_s3_delete"),
        sa.CheckConstraint("local_delete_performed = false", name="ck_durable_read_renewal_auth_no_local_delete"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["health_qualification_id"], ["evidence_recovery_durable_read_health_qualifications.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["health_qualification_receipt_id"], ["evidence_recovery_durable_read_health_qualification_receipts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["durable_lease_id"], ["evidence_recovery_durable_read_promotion_leases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["activation_receipt_id"], ["evidence_recovery_durable_read_promotion_receipts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["terminal_receipt_id"], ["evidence_recovery_durable_read_promotion_receipts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["prior_authorization_id"], ["evidence_recovery_durable_read_promotion_authorizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["phase_k_qualification_id"], ["evidence_recovery_routable_read_qualifications.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["replica_id"], ["evidence_recovery_replicas.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["health_qualified_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["durable_activated_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["requested_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["approved_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["rejected_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["terminal_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("health_qualification_id", name="uq_durable_read_renewal_auth_health_qualification"),
        sa.UniqueConstraint("organization_id", "authorization_hash", name="uq_durable_read_renewal_auth_org_hash"),
    )
    op.create_index("ix_drr_auth_org_claim", AUTH_TABLE, ["organization_id", "claim_id", "status"])
    op.create_index("ix_drr_auth_org_doc", AUTH_TABLE, ["organization_id", "document_id", "status"])
    for name, column in (
        ("ix_drr_auth_health_qualification", "health_qualification_id"),
        ("ix_drr_auth_health_receipt", "health_qualification_receipt_id"),
        ("ix_drr_auth_lease", "durable_lease_id"),
        ("ix_drr_auth_activation_receipt", "activation_receipt_id"),
        ("ix_drr_auth_terminal_receipt", "terminal_receipt_id"),
        ("ix_drr_auth_prior_authorization", "prior_authorization_id"),
        ("ix_drr_auth_k_qualification", "phase_k_qualification_id"),
        ("ix_drr_auth_replica", "replica_id"),
        ("ix_drr_auth_requester", "requested_by_id"),
        ("ix_drr_auth_approver", "approved_by_id"),
    ):
        op.create_index(name, AUTH_TABLE, [column])

    op.create_table(
        RECEIPT_TABLE,
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("authorization_id", sa.Uuid(), nullable=False),
        sa.Column("health_qualification_id", sa.Uuid(), nullable=False),
        sa.Column("durable_lease_id", sa.Uuid(), nullable=False),
        sa.Column("phase", sa.String(length=20), nullable=False),
        sa.Column("health_qualification_hash", sa.String(length=64), nullable=False),
        sa.Column("operational_evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("integrity_proof_hash", sa.String(length=64), nullable=False),
        sa.Column("request_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("authorization_hash", sa.String(length=64), nullable=False),
        sa.Column("receipt_hash", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("transitioned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("routable_authority_created", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("durable_read_route_created", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("read_path_switched", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("write_path_switched", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("document_storage_key_mutated", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("authoritative_storage_changed", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("destructive_action_performed", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("s3_delete_performed", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("local_delete_performed", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "phase IN ('requested', 'approved', 'rejected', 'expired', 'invalidated')",
            name="ck_durable_read_renewal_auth_receipt_phase",
        ),
        sa.CheckConstraint("routable_authority_created = false", name="ck_durable_read_renewal_auth_rec_no_route"),
        sa.CheckConstraint("durable_read_route_created = false", name="ck_durable_read_renewal_auth_rec_no_durable"),
        sa.CheckConstraint("read_path_switched = false", name="ck_durable_read_renewal_auth_rec_no_read"),
        sa.CheckConstraint("write_path_switched = false", name="ck_durable_read_renewal_auth_rec_no_write"),
        sa.CheckConstraint("document_storage_key_mutated = false", name="ck_durable_read_renewal_auth_rec_no_key"),
        sa.CheckConstraint("authoritative_storage_changed = false", name="ck_durable_read_renewal_auth_rec_no_auth"),
        sa.CheckConstraint("destructive_action_performed = false", name="ck_durable_read_renewal_auth_rec_no_dest"),
        sa.CheckConstraint("s3_delete_performed = false", name="ck_durable_read_renewal_auth_rec_no_s3_delete"),
        sa.CheckConstraint("local_delete_performed = false", name="ck_durable_read_renewal_auth_rec_no_local_delete"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["authorization_id"], [AUTH_TABLE + ".id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["health_qualification_id"], ["evidence_recovery_durable_read_health_qualifications.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["durable_lease_id"], ["evidence_recovery_durable_read_promotion_leases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "receipt_hash", name="uq_durable_read_renewal_auth_rec_org_hash"),
    )
    op.create_index("ix_drr_auth_receipt_time", RECEIPT_TABLE, ["authorization_id", "transitioned_at"])
    for name, column in (
        ("ix_drr_auth_rec_auth", "authorization_id"),
        ("ix_drr_auth_rec_health_qualification", "health_qualification_id"),
        ("ix_drr_auth_rec_lease", "durable_lease_id"),
        ("ix_drr_auth_rec_actor", "actor_id"),
    ):
        op.create_index(name, RECEIPT_TABLE, [column])


def downgrade() -> None:
    op.drop_table(RECEIPT_TABLE)
    op.drop_table(AUTH_TABLE)
